### ISSUE TITLE
Improve MIA descriptions in README 

### ISSUE THREAD

**Issue by Erdnaf** [privML/privacy-evaluator#115]
after receiving Franziskas Feedback after the current iteration

**Comment by Friedrich-Mueller** [comment]
After looking into the decision boundary issue, I feel like even for that we need a completely different README description as well, because the original idea does not cover the HopSkipJump algorithm at all..
This makes me wonder whether we should just leave it as it is, as the basic ideas are explained in the descriptions. Explaining what actually happens in the HopSkipJump algorithm seems rather extensive and does not really provide anything to the user - similiar to the thing with the original MIA by shokri et al.
