### ISSUE TITLE
Check out the decision boundary attack

### ISSUE THREAD

**Issue by Erdnaf** [privML/privacy-evaluator#152]
See why it's runnig slowly. Improve. Not a priority.

Read the Paper to know what the parameters are for

**Comment by Erdnaf** [comment]
Hey @Friedrich-Mueller I just looked into The Art implementation to see wehre the arguments are used and it seems that they are used in the Hot Ski Jump Class (https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/ee16efdc047808a183634eb678012502f8709c52/art/attacks/evasion/hop_skip_jump.py#L44 )

There is a paper linked that schould be helpfull too https://arxiv.org/pdf/1904.02144.pdf

I plan to look into that tomorrow in detail

**Comment by Friedrich-Mueller** [comment]
As we know, the decision boundary attack works by perturbating data records to find the decision boundary of a target model and train a binary classifier on that. In the paper you linked, I found the following "Each  step  carries  out  a  gradient update  from  the  boundary,  and  then  projects  back  to  the boundary again.". To compute that update the following is done:

            # Next compute the number of evaluations and compute the update
            num_eval = min(int(self.init_eval * np.sqrt(self.curr_iter + 1)), self.max_eval)

with the following default values:

max_iter: int = 50,
max_eval: int = 10000,
init_eval: int = 100

So it seems this line of code is done up to 10000 times, inside of a loop that is done 50 times, apparently for **each single image (and ALSO its perturbations?)**. Which might explain why for only 20 images, with max_iter=5, max_eval=5, int_eval=5, this takes 3 minutes in colab. Franziska has already mentioned that the advantage of the "conventional" MIA is that has better performance, but I did not expect such a big gap.

Thats just what I could gather within a few minutes, hence the vagueness, and due to this issue not being a priority.

**Comment by marisanest** [comment]
Can we close this issue now?

**Comment by Friedrich-Mueller** [comment]
I think so. I think its fair to say that we addressed the issue reasonably. Our solution might require the user to actually look into the hopskipjump paper himself if he really wants to understand the parameters, but, especially in this case, its really hard to "spoonfeed" the HopSkipJump algorithm itself. I think the readme and a look into the paper can suffice to understand what these parameters do in regards to runtime and performance of the attack. Thats basically what we did and I feel we understand these variables enough to perform some type of grid search with the aim of better attack performance, and we understand why the runtime is long with too high values.
