### ISSUE TITLE
Add description when the fit method can be called with different paramters to optimize attack models

### ISSUE THREAD

**Issue by Friedrich-Mueller** [privML/privacy-evaluator#195]

**Comment by marisanest** [comment]
I just researched a little bit, which parameters `ART` provides for the attack model fitting. There are not really many options via `ART` but I just documented everything - including ideas that are not yet possible with `ART`- below. I also added ideas, that are more general and not directly dependent on parameters but still are possible ways to optimize the attack model.

For the [MembershipInferenceBlackBox](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/inference/membership_inference/black_box.py) fitting:
* There are no direct parameters for the fit function to optimize the attack model
* In general: Providing more training data
* In general: Providing an own `attack_model` which performance better
* If no custom `attack_model` is provided and the `attack_model_type` is `'nn'`: You could adjust the `epochs`, `batch_size`, `learning_rate` of the training process via calling `attack.art_attack.epochs = ...`
*  If no custom `attack_model` is provided and the `attack_model_type` is `'gb'` or `'rf'`: For both types `sklearn` implementations are used. You could check the documentation of sklearn (there are plenty parameters to tweak these models) and then call something like `attack.art_attack.attack_model.<parameter_name> = ... `

This is all not really pretty due to a lack of options via the `ART` framework.

**Comment by Friedrich-Mueller** [comment]
> 
> 
> I just researched a little bit about which parameters `ART` provides for the `attack_model` fitting. There are not really many options via `ART` but I just documented everything - including ideas that are not yet possible with `ART`- below. I also added ideas, that are more general and not directly dependent on parameters but still are possible ways to optimize the `attack_model`.
> 
> For the [MembershipInferenceBlackBox](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/inference/membership_inference/black_box.py) fitting:
> 
>     * `ART` do not provide any direct parameters for the `fit` function to optimize the attack_model
> 
>     * In general: You could provide more training data
> 
>     * In general: You could provide your own `attack_model` which performance better
> 
>     * If no custom `attack_model` is provided and the `attack_model_type` is `'nn'`: You could adjust the `epochs`, `batch_size`, `learning_rate` of the training process via calling `attack.art_attack.epochs = ...`
> 
>     * If no custom `attack_model` is provided and the `attack_model_type` is `'gb'` or `'rf'`: For both types `sklearn` implementations are used. You could check the documentation of sklearn (there are plenty parameters to tweak these models) and then call something like `attack.art_attack.attack_model.<parameter_name> = ... `
> 
> 
> This is all not really pretty due to a lack of options via the `ART` framework.
> 
> For the [MembershipInferenceBlackBoxRuleBased](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/inference/membership_inference/black_box_rule_based.py) fitting:
> 
>     * There is no `fit` function
> 
> 
> For the [LabelOnlyDecisionBoundary](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/attacks/inference/membership_inference/label_only_boundary_distance.py) fitting:
> 
>     * In ART the `fit` function is called `calibrate_distance_threshold`
> 
>     * In general: You could provide more training data
> 
>     * The following parameters to optimize the `attack_model` are provided by `ART`
> 
> 
> ```python
> :Keyword Arguments for HopSkipJump:
>             *norm*: Order of the norm. Possible values: "inf", np.inf or 2.
>             *max_iter*: Maximum number of iterations.
>             *max_eval*: Maximum number of evaluations for estimating gradient.
>             *init_eval*: Initial number of evaluations for estimating gradient.
>             *init_size*: Maximum number of trials for initial generation of adversarial examples.
> ```
> 
> I have not added any documentation to the code yet. It's just a summary so that we can decide where this info should go. What do you think @Friedrich-Mueller?

This whole post is pretty neat and we should discuss incorporating it into the readme? Below the attack descriptions? Or maybe we split this post and append a piece of it to each of the attacks?

**Comment by marisanest** [comment]
Yes, I think the `README` is a good place to provide some general info on how to optimize the fitting process. I think splitting it and adding it for each attack respectively makes the most sense to provide the info in the right context. Nevertheless, I would still add the parameters for the `LabelOnlyDecisionBoundary` to the docstrings of the `fit()` method.
