### ISSUE TITLE
Having trouble testing code

### ISSUE THREAD

**Issue by Erdnaf** [privML/privacy-evaluator#33]
I am working on #17 and tried to verify my changes, but i have trouble importing and testing my code

I am importing only within the project with statements like `from privacy_evaluator.attacks.sample_attack import Sample_Attack`when the error occurs.

When testing with sometting like `python3 tests/class_test.py` from the project root, I always get the error `ModuleNotFoundError: No module named 'privacy_evaluator'`

How do i get the project working?
this also happens when i try the tests on #18 and try to execute the tests

**Comment by jtorhoff** [comment]
The semantics of importing packages and modules in Python seem a bit finicky. Had the same issue when setting up the model (#19). Putting the training script inside that models directory felt wrong but I couldn't put it anywhere else and just gave up by that point. The issue stems from running it as a script, see the [StackOverflow answer](https://stackoverflow.com/a/14132912) here. 

The only proper solution seems to me to create a `setup.py` in the root directory that would install the package globally, then you can import it everywhere. See this [StackOverflow answer](https://stackoverflow.com/a/28154841) and scroll down to `Solution #3`. I don't have the time at the moment to do it but I can look into doing that tomorrow.

@adrinjalali can you confirm that creating a `setup.py` would be the way to go, or are there better alternatives?

**Comment by marisanest** [comment]
I had the same issue while testing. I just added a `__init__.py` file into the `tests` directory and it worked and you should also put a `__init__.py`  into the `privacy_evaluator.attacks` directory.

**Comment by Erdnaf** [comment]
Okay thanks for the answers. 
By adding some `__init__.py` files and caling the function from the test environment I somehow got it working. I didn't need to setup all the tiongs globaly like @jtorhoff suggestested

**Comment by adrinjalali** [comment]
Reopening this since I think this needs to be addressed a bit better.

If you do a statement such as `from privacy_evaluator.attacks import blah`, as long as you're not in the folder where `privacy_evaluator` is a sub-folder, it imports from your global installation.

If you do a relative import such as `from .attacks import blah`, it imports locally, example [here](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/ensemble/_hist_gradient_boosting/loss.py)

There are different conventions followed by different projects. Some projects ban any relative import statement, such as `pandas` ([example](https://github.com/pandas-dev/pandas/blob/master/pandas/core/arrays/_ranges.py)), and some projects like `scikit-learn` allow relative import in all the code base, except the tests.

To me, it doesn't matter which one you chose, I'd chose the latter, but only because I'm a scikit-learn core-dev and I'm used too it.

In any case, your tests should never have relative imports.

Regardless, you definitely need a `setup.py` to build the package and allow users to work with this library. All your tests and examples and documentation, should assume `privacy_evaluator` is installed as a package, and use it that way accordingly.

**Comment by marisanest** [comment]
@adrinjalali thanks for your feedback! We now added a `setup.py` to properly installed `privacy_evaluator` as a package in PR #73.
