### ISSUE TITLE
Create a repo for Team1 and fork it / or branch

### ISSUE THREAD

**Issue by budmil** [privML/privacy-evaluator#37]
Figure out what exactly we do on a Gitter discussion.

**Comment by blauertee** [comment]
This was my proposal and the three possibilities we discussed on [gitter](https://gitter.im/privML/Group-1?at=6092901dd261cc4d74abef1b) 


#### Use another repo on the privML Organization
There is no possibility to fork into an organization repo of the same organization, so we would have to clone and push into a new repository (or copy the repo in another way, it will not be linked as a fork in any way), this will make merging to main really hard and does not seem like a valid option to me.

#### Use a private fork of any team member as w&p repo
The disadvantage here is, that we can not link issues to backlog items, which is annoying and will create organizational overhead.

#### Use a separate branch at privML/privacy-evaluator
I know that we already discussed this, but I'm still thinking about it, since this wouldn't have any of the disadvantages the other two possibilities have. I think our POs point was that then the stakeholders would have changes, that might not be accepted in the end, on the main repo. But they could see these changes anyway since our fork would also be public. And I would see it more as an advantage that all the work done, even if it contained mistakes and has to be taken back, is transparent to everyone who joins the repo, so the whole development history is visible to everyone looking at the repo. And the main branch would still only contain a version of the software that only contains working increments, accepted by our PO.

### Solution:

We all including our PO agreed to go with the third option.

Since (in the best case) we would merge the work and progress branch into main after each sprint and the w&p-branch would disappear then, I thought it made sense to call our team one branch [team1sprint2](https://github.com/privML/privacy-evaluator/tree/team1sprint2) for this sprint. 

**Any merges during the sprint done by team1 should go there instead of into main from now on.**

I also added `team2needed` label since this is probably important to you too. And you might create a `team2sprint1` branch.
